import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Navbar from "../components/Navbar";
import ParallaxWrapper from "../components/ParallaxWrapper";
import { AuthProvider } from "@/context/AuthContext";
import { Almarai } from "next/font/google";
import { NavbarProvider, useNavbar } from "@/context/NavBarContext";
import NavbarWrapper from "@/components/navbarWrapper";
import { ToastContainer } from 'react-toastify';
import { SpeedInsights } from "@vercel/speed-insights/next"

const almarai = Almarai({
  subsets: ["arabic"],
  weight: ["300", "400", "700", "800"],
});

export const metadata = {
  title: "InFocusMedia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <head>
        {/* Removed Google Fonts <link> in favor of next/font */}
        <title>Infocus Media - Creative Agency</title>
        <meta
          name="description"
          content="Infocus Media: Born from Emirati soil, our roots run deep and our vision soars high. Explore our case studies, services, and creative work."
        />
        <meta property="og:title" content="Infocus Media - Creative Agency" />
        <meta
          property="og:description"
          content="Explore our case studies, services, and creative work."
        />
        <meta property="og:image" content="/logo.png" />
        <meta property="og:type" content="website" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={`relative`}>
        {/* 👇 Fixed background layer for mix-blend-difference to work */}
        {/* <div className="fixed inset-0 z-0 bg-red" /> */}
        <AuthProvider>
          <NavbarProvider>
            <NavbarWrapper />
            {children}
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
              toastStyle={{
                fontSize: '14px',
                fontFamily: 'inherit'
              }}
            />
          </NavbarProvider>
        </AuthProvider>
        <SpeedInsights/>
      </body>
    </html>
  );
}
